#!/usr/bin/env python3
"""writes scene/components/player.rml: one frame solo per character (mario, luigi, wario, waluigi) inside a
character solo. the script sets Player.pose every frame (the rom picks the walk frame from a speed counter, so
poses are single frames) and flips the whole instance for facing; Player.character picks the solo. the
component is instanced by the script (artboard:instance), so its state machine may read the view model.
ids: 1:1xx structure, 1:2xx mario, 1:25x wario, 1:3xx luigi, 1:35x waluigi, 1:4xx animations, 1:5xx machine,
1:1xxx the rest. run: python3 tools/gen_player_rml.py"""
import json, os
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ids = json.load(open(os.path.join(root, 'tools/asset_ids.json')))
def I(n): return f'8:{ids["image/" + n]}'
CHARS = [('mario', 'Mario', '1:110', 200, '9:141', '1:420', '1:510'), ('luigi', 'Luigi', '1:120', 300, '9:142', '1:421', '1:511'), ('wario', 'Wario', '1:130', 250, '9:143', '1:422', '1:512'), ('waluigi', 'Waluigi', '1:140', 350, '9:144', '1:423', '1:513')]
POSES = [('stand', 'stand', '9:131'), ('walk', 'walk', '9:132'), ('skid', 'skid', '9:133'), ('jump', 'jump', '9:134'), ('fall', 'walk', '9:135'), ('stun', 'stun', '9:136'), ('kick', 'kick', '9:137'), ('dead', 'dead', '9:138')]
n = [1000]
def nid():
    n[0] += 1
    return f'1:{n[0]}'
def enum_cond(to, prop, value):
    return f"""                    <StateTransition stateToId="{to}" duration="0" id="{nid()}">
                        <TransitionViewModelCondition opValue="equal" id="{nid()}">
                            <TransitionPropertyViewModelComparator id="{nid()}">
                                <BindablePropertyEnum id="{nid()}">
                                    <DataBindContext sourcePathIds="9:300-{prop}" propertyKey="637" id="{nid()}"/>
                                </BindablePropertyEnum>
                            </TransitionPropertyViewModelComparator>
                            <TransitionValueEnumComparator value="{value}" id="{nid()}"/>
                        </TransitionViewModelCondition>
                    </StateTransition>"""
L = ['<Rive version="1" kind="fragment">',
     '    <!-- Player component: 16x16, generated by tools/gen_player_rml.py (see its header) -->',
     '    <Artboard isComponent="true" defaultStateMachineId="1:500" viewModelId="9:300" viewModelInstanceId="9:301" width="16" height="16" styleId="1:101" x="0" y="-120" name="Player" id="1:100">',
     '        <LayoutComponentStyle name="Player Style" id="1:101"/>',
     '        <Solo activeComponentId="1:110" name="Character" id="1:105">']
for key, title, solo, base, _, _, _ in CHARS:
    L.append(f'            <Solo activeComponentId="1:{base}" name="{title}" id="{solo}">')
    for k, (pose, frame, _) in enumerate(POSES):
        L.append(f'                <Image assetId="{I(key + "_" + frame)}" originX="0" originY="0" name="{pose}" id="1:{base + k}"/>')
    L.append('            </Solo>')
L.append('        </Solo>')
L.append('        <!-- one frame per pose; each keys every character so the character layer only has to pick one -->')
for k, (pose, _, _) in enumerate(POSES):
    L.append(f'        <LinearAnimation loopValue="loop" duration="1" name="{pose}" id="1:40{k}">')
    for key, title, solo, base, _, _, _ in CHARS:
        L.append(f'            <KeyedObject objectId="{solo}" id="{nid()}"><KeyedProperty propertyKey="296" id="{nid()}"><KeyFrameId value="1:{base + k}" frame="0" id="{nid()}"/></KeyedProperty></KeyedObject>')
    L.append('        </LinearAnimation>')
for key, title, solo, base, _, anim, _ in CHARS:
    L.append(f'        <LinearAnimation loopValue="loop" duration="1" name="Be {title}" id="{anim}">')
    L.append(f'            <KeyedObject objectId="1:105" id="{nid()}"><KeyedProperty propertyKey="296" id="{nid()}"><KeyFrameId value="{solo}" frame="0" id="{nid()}"/></KeyedProperty></KeyedObject>')
    L.append('        </LinearAnimation>')
L.append('        <StateMachine name="Player" id="1:500">')
L.append('            <!-- Character: which one, from Player.character -->')
L.append('            <StateMachineLayer name="Character" id="1:501">')
L.append('                <AnyState x="60" y="-100" id="1:502"/>')
L.append('                <ExitState x="760" y="-100" id="1:503"/>')
L.append('                <EntryState x="0" y="0" id="1:504">')
L.append('                    <StateTransition stateToId="1:510" id="1:505"/>')
L.append('                </EntryState>')
for i, (key, title, solo, base, enum, anim, state) in enumerate(CHARS):
    L.append(f'                <AnimationState animationId="{anim}" x="{160 + 150 * i}" y="0" id="{state}">')
    for j, (_, _, _, _, enum2, _, state2) in enumerate(CHARS):
        if j != i:
            L.append(enum_cond(state2, '9:310', enum2))
    L.append('                </AnimationState>')
L.append('            </StateMachineLayer>')
L.append('            <!-- Pose: one state per frame, from Player.pose -->')
L.append('            <StateMachineLayer name="Pose" id="1:515">')
L.append('                <AnyState x="60" y="-100" id="1:516"/>')
L.append('                <ExitState x="1400" y="-100" id="1:517"/>')
L.append('                <EntryState x="0" y="0" id="1:518">')
L.append('                    <StateTransition stateToId="1:520" id="1:519"/>')
L.append('                </EntryState>')
for i, (pose, _, enum) in enumerate(POSES):
    L.append(f'                <AnimationState animationId="1:40{i}" x="{160 + 150 * i}" y="0" id="1:52{i}">')
    for j, (_, _, enum2) in enumerate(POSES):
        if j != i:
            L.append(enum_cond(f'1:52{j}', '9:311', enum2))
    L.append('                </AnimationState>')
L.append('            </StateMachineLayer>')
L.append('        </StateMachine>')
L.append('    </Artboard>')
L.append('    <ComponentAsset artboardId="1:100" name="Player" id="1:102"/>')
L.append('</Rive>')
path = os.path.join(root, 'scene/components/player.rml')
open(path, 'w').write('\n'.join(L) + '\n')
print('wrote', path)
