#!/usr/bin/env python3
"""writes scene/stages/<name>.rml, one component artboard per stage: the art (the ripped strips placed by
hand below) and the StageData view model instance holding the stage's tile map, which scripts/stage.luau reads
to build the collision grid, the pipes, the pow and the player starts. the map is derived from the same
rectangles the art is placed from, so the two cannot drift. adding a stage: add an entry to STAGES, run this,
then give scene/game.rml a placement in the Stages solo, a Stage layer state and a stageN input (see
docs/rules.md, "stages"). ids: stage k uses 2k:xxx, its view model instance 9:100k.
run: python3 tools/gen_stages_rml.py"""
import json, os
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ids = json.load(open(os.path.join(root, 'tools/asset_ids.json')))
def I(n): return f'8:{ids["image/" + n]}'

# each stage: solid platforms as (image, x, y, w, h), pipes and the pow are fixed for now (the top pipes spawn,
# the bottom ones recycle), starts as (x, y) for players 1..4
PIPES_TOP = [(0, 16), (224, 16)]
PIPES_BOTTOM = [(0, 176), (224, 176)]
STAGES = [
    {
        'name': 'typical', 'title': 'Typical', 'pow': (120, 152),
        'platforms': [('ledge_ul', 0, 48, 96, 16), ('ledge_ur', 160, 48, 96, 16), ('platform_c', 64, 96, 128, 16),
                      ('stub_l', 0, 112, 32, 16), ('stub_r', 224, 112, 32, 16), ('ledge_ll', 0, 160, 96, 16),
                      ('ledge_lr', 160, 160, 96, 16), ('floor', 0, 208, 256, 32)],
        'starts': [(64, 192), (176, 192), (8, 144), (232, 144)],
    },
    {
        'name': 'steps', 'title': 'Steps', 'pow': (120, 152),
        'platforms': [('ledge_ul', 0, 48, 96, 16), ('ledge_ur', 160, 48, 96, 16), ('platform_c', 64, 112, 128, 16),
                      ('stub_l', 0, 128, 32, 16), ('stub_r', 224, 128, 32, 16), ('ledge_ll', 0, 160, 96, 16),
                      ('ledge_lr', 160, 160, 96, 16), ('floor', 0, 208, 256, 32)],
        'starts': [(64, 192), (176, 192), (8, 144), (232, 144)],
    },
]

def render_map(stage):
    g = [['.'] * 32 for _ in range(30)]
    for _, x, y, w, h in stage['platforms']:
        for r in range(y // 8, (y + h) // 8):
            for c in range(x // 8, (x + w) // 8):
                g[r][c] = '#'
    for x, y in PIPES_TOP:
        g[y // 8][x // 8] = 'T'
    for x, y in PIPES_BOTTOM:
        g[y // 8][x // 8] = 'B'
    px, py = stage['pow']
    g[py // 8][px // 8] = 'P'
    for i, (x, y) in enumerate(stage['starts']):
        g[y // 8][x // 8] = str(i + 1)
    return '|'.join(''.join(r) for r in g)

os.makedirs(os.path.join(root, 'scene/stages'), exist_ok=True)
for k, stage in enumerate(STAGES, start=1):
    p = 20 + k  # id prefix
    n = [200]
    def nid():
        n[0] += 1
        return f'{p}:{n[0]}'
    L = ['<Rive version="1" kind="fragment">',
         f'    <!-- stage "{stage["name"]}": the arena art, placed by scene/game.rml in the Stages solo. its StageData instance',
         '         (in scene/data/view_models.rml) carries the tile map scripts/stage.luau plays. generated by',
         f'         tools/gen_stages_rml.py, ids {p}:xxx -->',
         f'    <Artboard isComponent="true" defaultStateMachineId="{p}:500" viewModelId="9:1000" viewModelInstanceId="9:100{k}" width="256" height="240" styleId="{p}:101" x="0" y="{-960 - 300 * k}" name="Stage{stage["title"]}" id="{p}:100">',
         f'        <LayoutComponentStyle name="Stage{stage["title"]} Style" id="{p}:101"/>']
    for name, x, y in [('pipe_tl', 0, 16), ('pipe_tr', 224, 16)]:
        L.append(f'        <Image assetId="{I(name)}" x="{x}" y="{y}" originX="0" originY="0" name="{name}" id="{nid()}"/>')
    for name, x, y, w, h in stage['platforms']:
        L.append(f'        <Image assetId="{I(name)}" x="{x}" y="{y}" originX="0" originY="0" name="{name}" id="{nid()}"/>')
    for name, x, y in [('pipe_bl', 0, 176), ('pipe_br', 224, 176)]:
        L.append(f'        <Image assetId="{I(name)}" x="{x}" y="{y}" originX="0" originY="0" name="{name}" id="{nid()}"/>')
    L.append(f'''        <StateMachine name="Binds" id="{p}:500">
            <StateMachineLayer name="Layer" id="{p}:501">
                <AnyState x="60" y="-100" id="{p}:502"/>
                <ExitState x="360" y="-100" id="{p}:503"/>
                <EntryState x="0" y="0" id="{p}:504"/>
            </StateMachineLayer>
        </StateMachine>''')
    L.append('    </Artboard>')
    L.append(f'    <ComponentAsset artboardId="{p}:100" name="Stage{stage["title"]}" id="{p}:102"/>')
    L.append('</Rive>')
    path = os.path.join(root, 'scene/stages', stage['name'] + '.rml')
    open(path, 'w').write('\n'.join(L) + '\n')
    print('wrote', path)

# the view model: one instance per stage plus an empty one for the unused Game.stageN slots
vm = ['    <!-- a stage\'s data: its name and the tile map scripts/stage.luau reads (see the header of that file for the',
      '         characters). one exported instance per stage in scene/stages, each stage artboard bound to its own. -->',
      '    <ViewModel defaultInstanceId="9:1001" name="StageData" id="9:1000">',
      '        <ViewModelPropertyString name="name" id="9:1010"/>',
      '        <ViewModelPropertyString name="map" id="9:1011"/>']
for k, stage in enumerate(STAGES, start=1):
    vm.append(f'        <ViewModelInstance exports="true" name="{stage["title"]}" id="9:100{k}">')
    vm.append(f'            <ViewModelInstanceString propertyValue="{stage["name"]}" viewModelPropertyId="9:1010" id="9:11{k}0"/>')
    vm.append(f'            <ViewModelInstanceString propertyValue="{render_map(stage)}" viewModelPropertyId="9:1011" id="9:11{k}1"/>')
    vm.append('        </ViewModelInstance>')
vm.append('        <ViewModelInstance exports="true" name="Empty" id="9:1009">')
vm.append('            <ViewModelInstanceString propertyValue="" viewModelPropertyId="9:1010" id="9:1090"/>')
vm.append('            <ViewModelInstanceString propertyValue="" viewModelPropertyId="9:1011" id="9:1091"/>')
vm.append('        </ViewModelInstance>')
vm.append('    </ViewModel>')
block = '\n'.join(vm)
vpath = os.path.join(root, 'scene/data/view_models.rml')
s = open(vpath).read()
start = s.find('    <!-- a stage\'s data')
if start >= 0:
    end = s.index('    </ViewModel>', start) + len('    </ViewModel>')
    s = s[:start] + block + s[end:]
else:
    s = s.replace('</Rive>', block + '\n</Rive>')
open(vpath, 'w').write(s)
print('view model StageData written with', len(STAGES), 'stages')
