#!/usr/bin/env python3
"""writes scene/assets.rml from the asset folders. image and audio ids are 8:<crc of the name>, so they
never change when assets are added; the table lands in tools/asset_ids.json. font 8:850, scripts 8:9xx. run after slicing: python3 tools/gen_assets_rml.py"""
import os, json, zlib
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def pngs(d):
    return sorted(f[:-4] for f in os.listdir(os.path.join(root, d)) if f.endswith('.png'))
ids = {}
def stable_id(kind, name):
    """8:<hash> ids never move when assets are added, so hand written rml can hardcode them."""
    n = 1000 + zlib.crc32(f"{kind}/{name}".encode()) % 60000
    while n in ids.values():
        n += 1
    ids[f"{kind}/{name}"] = n
    return f"8:{n}"
lines = ['<Rive version="1" kind="fragment">',
         '    <!-- generated by tools/gen_assets_rml.py, do not edit by hand. every image is nearest sampled. -->',
         '    <!-- stage strips -->']
for n in pngs('assets/stage'):
    lines.append(f'    <ImageAsset file="assets/stage/{n}.png" samplerFilter="1" name="{n}" id="{stable_id("image", n)}"/>')
lines.append('    <!-- sprite frames -->')
for n in pngs('assets/sprites'):
    lines.append(f'    <ImageAsset file="assets/sprites/{n}.png" samplerFilter="1" name="{n}" id="{stable_id("image", n)}"/>')
lines.append('    <!-- sound effects, the mushroom kingdom rips (docs/rules.md has the credits) -->')
for n in sorted(f[:-4] for f in os.listdir(os.path.join(root, 'assets/sfx')) if f.endswith('.wav')):
    lines.append(f'    <AudioAsset file="assets/sfx/{n}.wav" name="{n}" id="{stable_id("audio", n)}"/>')
lines.append('    <!-- music, cut by tools/cut_music.py: the intro plays once, the loop is scheduled gaplessly by scripts/sfx.luau -->')
for n in sorted(f[:-5] for f in os.listdir(os.path.join(root, 'assets/music')) if f.endswith('.flac')):
    lines.append(f'    <AudioAsset file="assets/music/{n}.flac" volume="0.5" name="{n}" id="{stable_id("audio", n)}"/>')
lines.append('    <!-- font, ofl licensed -->')
lines.append('    <FontAsset file="assets/fonts/PressStart2P-Regular.ttf" name="PressStart2P" id="8:850"/>')
lines.append('    <!-- scripts: modules first, game last, because require only finds modules declared above. folderPath makes them require("scripts/<name>") -->')
modules = ['stage', 'physics', 'input', 'sfx', 'world', 'players', 'enemies', 'fireballs']
for i, m in enumerate(modules):
    lines.append(f'    <ScriptAsset file="scripts/{m}.luau" folderPath="scripts" isModule="true" name="{m}" id="8:{901+i}"/>')
lines.append('    <ScriptAsset file="scripts/game.luau" folderPath="scripts" name="game" id="8:990"/>')
lines.append('    <!-- tests, kept out of the rev by excludeFromRev; declared here so they see the modules above -->')
tests = sorted(f[:-5] for f in os.listdir(os.path.join(root, 'scripts')) if f.endswith('_test.luau'))
for i, t in enumerate(tests):
    lines.append(f'    <ScriptAsset file="scripts/{t}.luau" folderPath="scripts" name="{t}" id="8:{951+i}"/>')
lines.append('</Rive>')
open(os.path.join(root, 'scene/assets.rml'), 'w').write('\n'.join(lines) + '\n')
json.dump(ids, open(os.path.join(root, 'tools/asset_ids.json'), 'w'), indent=1, sort_keys=True)
print('wrote scene/assets.rml with', len(lines), 'lines')
