#!/usr/bin/env python3
"""writes scene/components/{hud_slot,overlay,menu}.rml: the nested artboard components scene/game.rml places,
each bound to its own view model instance through the placement's dataBindPathIds.

placed components cannot use state machine conditions on their view model (a placement's machine reads the
artboard's authored instance, not the placement's), so every visual is a direct property bind: opacities
from numbers (0 or 1, or a formula band on an index), text runs from strings, positions from numbers.
each artboard still carries an empty state machine, binds only run with one.
ids: hud slot 10:xxx (view model 9:8xx), menu 11:xxx (9:9xx), overlay 12:xxx (9:95x).
run: python3 tools/gen_ui_rml.py"""
import json, os
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ids = json.load(open(os.path.join(root, 'tools/asset_ids.json')))
def I(n): return f'8:{ids["image/" + n]}'
FONT = '8:850'
CHARS = ['mario', 'luigi', 'wario', 'waluigi']
MARKER_COLOURS = ['FFFFFFFF', 'FF3CBCFC', 'FFF8B800', 'FFC060FF']
ORANGE = 'FFEA9E22'

class Ids:
    def __init__(self, prefix, start):
        self.prefix, self.n = prefix, start
    def __call__(self):
        self.n += 1
        return f'{self.prefix}:{self.n}'

def empty_machine(prefix, nid):
    return f'''        <StateMachine name="Binds" id="{prefix}:500">
            <StateMachineLayer name="Layer" id="{prefix}:501">
                <AnyState x="60" y="-100" id="{nid()}"/>
                <ExitState x="360" y="-100" id="{nid()}"/>
                <EntryState x="0" y="0" id="{nid()}"/>
            </StateMachineLayer>
        </StateMachine>'''

def text(x, y, s, colour, name, nid, binds='', origin_x='0.5'):
    style = nid()
    return f'''        <Text x="{x}" y="{y}" sizingValue="autoWidth" originX="{origin_x}" originY="0" name="{name}" id="{nid()}">
{binds}            <TextStylePaint fontSize="8" fontAssetId="{FONT}" name="Style" id="{style}">
                <Fill name="Fill" id="{nid()}"><SolidColor colorValue="{colour}" name="Colour" id="{nid()}"/></Fill>
            </TextStylePaint>
            <TextValueRun styleId="{style}" text="{s}" name="Run" id="{nid()}"/>
        </Text>'''

def bind(path, key, nid, converter=None):
    conv = f' converterId="{converter}"' if converter else ''
    return f'            <DataBindContext sourcePathIds="{path}" propertyKey="{key}"{conv} id="{nid()}"/>\n'

def band(k, name, cid):
    """max(0, 1 - sqrt((input - k) * (input - k))): 1 when the index is k, 0 on every other integer"""
    return f'''    <DataConverterFormula name="{name}" id="{cid}">
        <FormulaTokenFunction functionType="1"/>
        <FormulaTokenValue operationValue="0"/>
        <FormulaTokenArgumentSeparator/>
        <FormulaTokenValue operationValue="1"/>
        <FormulaTokenOperation operationType="1"/>
        <FormulaTokenFunction functionType="5"/>
        <FormulaTokenParenthesisOpen/>
        <FormulaTokenInput/>
        <FormulaTokenOperation operationType="1"/>
        <FormulaTokenValue operationValue="{k}"/>
        <FormulaTokenParenthesisClose/>
        <FormulaTokenOperation operationType="2"/>
        <FormulaTokenParenthesisOpen/>
        <FormulaTokenInput/>
        <FormulaTokenOperation operationType="1"/>
        <FormulaTokenValue operationValue="{k}"/>
        <FormulaTokenParenthesisClose/>
        <FormulaTokenParenthesisClose/>
        <FormulaTokenParenthesisClose/>
    </DataConverterFormula>'''

def one_minus(name, cid):
    return f'''    <DataConverterFormula name="{name}" id="{cid}">
        <FormulaTokenValue operationValue="1"/>
        <FormulaTokenOperation operationType="1"/>
        <FormulaTokenInput/>
    </DataConverterFormula>'''

def hud_slot():
    nid = Ids('10', 1000)
    L = ['<Rive version="1" kind="fragment">',
         "    <!-- one player's hud: a 60x17 box with the character's letter and five coin fills, from HudSlot",
         '         (letter 0..3 picks the box through a band formula, coins lights the fills through the slot range mappers,',
         '         shown 0 or 1 is the opacity). placed four times by scene/game.rml, each bound to its own Game.hudN',
         '         instance. generated by tools/gen_ui_rml.py, ids 10:xxx -->',
         '    <Artboard isComponent="true" defaultStateMachineId="10:500" viewModelId="9:800" viewModelInstanceId="9:801" width="60" height="17" styleId="10:101" x="0" y="-160" name="HudSlot" id="10:100">',
         '        <LayoutComponentStyle name="HudSlot Style" id="10:101"/>',
         '        <Node name="Slot" id="10:102">',
         '            <DataBindContext sourcePathIds="9:800-9:812" propertyKey="18" id="10:103"/>']
    for k, c in enumerate(CHARS):
        L.append(f'            <Image assetId="{I("hud_" + ("wl" if c == "waluigi" else c[0]))}" originX="0" originY="0" opacity="0" name="{c}" id="10:20{k}">')
        L.append(f'                <DataBindContext sourcePathIds="9:800-9:810" propertyKey="18" converterId="10:71{k}" id="10:23{k}"/>')
        L.append('            </Image>')
    for k in range(5):
        L.append(f'            <Image assetId="{I("hud_coin")}" x="{16 + 8 * k}" y="4" originX="0" originY="0" opacity="0" name="coin_{k + 1}" id="10:21{k}">')
        L.append(f'                <DataBindContext sourcePathIds="9:800-9:811" propertyKey="18" converterId="10:70{k}" id="10:22{k}"/>')
        L.append('            </Image>')
    L.append('        </Node>')
    L.append(empty_machine('10', nid))
    L.append('    </Artboard>')
    L.append('    <ComponentAsset artboardId="10:100" name="HudSlot" id="10:104"/>')
    for k in range(5):
        L.append(f'    <DataConverterRangeMapper minInput="{k}" maxInput="{k + 1}" minOutput="0" maxOutput="1" clampLower="true" clampUpper="true" name="Hud coin slot {k + 1}" id="10:70{k}"/>')
    for k, c in enumerate(CHARS):
        L.append(band(k, f'Hud letter {c}', f'10:71{k}'))
    L.append('</Rive>')
    return '\n'.join(L) + '\n'

def overlay():
    nid = Ids('12', 1000)
    L = ['<Rive version="1" kind="fragment">',
         '    <!-- the in-round overlays: the pause banner and the winner banner, from Overlay (pauseShown and winnerShown',
         '         are opacities, winnerText the run). placed on top of everything by scene/game.rml. generated by',
         '         tools/gen_ui_rml.py, ids 12:xxx -->',
         '    <Artboard isComponent="true" defaultStateMachineId="12:500" viewModelId="9:950" viewModelInstanceId="9:951" width="256" height="240" styleId="12:101" x="0" y="-420" name="Overlay" id="12:100">',
         '        <LayoutComponentStyle name="Overlay Style" id="12:101"/>']
    L.append(text(128, 124, 'PAUSE', 'FFFFFFFF', 'PauseText', nid, bind('9:950-9:960', 18, nid)))
    L.append(text(128, 124, 'WINS', 'FFFFFFFF', 'WinnerText', nid, bind('9:950-9:961', 18, nid)).replace(
        'name="Run" id=', 'name="Run" id=').replace('<TextValueRun', '<TextValueRun').replace(
        '            <TextValueRun styleId', '            <TextValueRun styleId'))
    # bind the winner run's text: rewrite the last run to hold the bind as a child
    L[-1] = L[-1].replace('text="WINS" name="Run" id="', 'text="WINS" name="Run" id="').replace(
        '/>\n        </Text>', '>\n                <DataBindContext sourcePathIds="9:950-9:962" propertyKey="268" id="' + nid() + '"/>\n            </TextValueRun>\n        </Text>')
    L.append(empty_machine('12', nid))
    L.append('    </Artboard>')
    L.append('    <ComponentAsset artboardId="12:100" name="Overlay" id="12:102"/>')
    L.append('</Rive>')
    return '\n'.join(L) + '\n'

# a 2x2 grid of 60x80 cards (mario, luigi / wario, waluigi), 8 px between columns, 16 between rows, START below
CARD_X = [64, 132, 64, 132]
CARD_Y_ROW = [28, 28, 124, 124]
CARD_W, CARD_H = 60, 80
START_Y = 216
CURSOR_OUT = 4 # every cursor is the target's rect grown by this; the dashes tell them apart
DASH = 4
CURSOR_PROPS = ['9:910', '9:911', '9:912', '9:913']
LOCK_PROPS = ['9:920', '9:921', '9:922', '9:923']
MODE_PROPS = ['9:930', '9:931', '9:932', '9:933']

def menu():
    nid = Ids('11', 1000)
    L = ['<Rive version="1" kind="fragment">',
         '    <!-- the start menu, smb3 style: black screen, nes text, one card per character and START below, from Menu.',
         '         each cursor outline and nP marker follows Menu.cursorN (x y w h markerX markerY shown, laid out by',
         '         scripts/menu.luau), a card hops to its jump frame when lockN is 1, and modeN is the label under the',
         '         name (CPU, OFF or nothing). placed in the Title solo by scene/game.rml. generated by',
         '         tools/gen_ui_rml.py, ids 11:xxx. card geometry must match Menu.CARD_RECTS -->',
         '    <Artboard isComponent="true" defaultStateMachineId="11:500" viewModelId="9:900" viewModelInstanceId="9:901" width="256" height="240" styleId="11:101" x="0" y="-700" name="Menu" id="11:100">',
         '        <LayoutComponentStyle name="Menu Style" id="11:101"/>']
    # markers and cursors first: they draw on top of the cards
    for i in range(4):
        cp = CURSOR_PROPS[i]
        binds = bind(f'9:900-{cp}-9:714', 13, nid) + bind(f'9:900-{cp}-9:715', 14, nid) + bind(f'9:900-{cp}-9:716', 18, nid)
        L.append(text(CARD_X[i] + 22, CARD_Y_ROW[i] - 16, f'{i + 1}P', MARKER_COLOURS[i], f'Marker{i + 1}', nid, binds, origin_x='0'))
    for i in range(4):
        cp = CURSOR_PROPS[i]
        # one rect for every cursor, a 4 on 4 off dash, each slot's pattern shifted 2 px along
        L.append(f'        <Shape x="{CARD_X[i] - CURSOR_OUT + 0.5}" y="{CARD_Y_ROW[i] - CURSOR_OUT + 0.5}" name="Cursor{i + 1}" id="{nid()}">')
        L.append(bind(f'9:900-{cp}-9:710', 13, nid).rstrip('\n'))
        L.append(bind(f'9:900-{cp}-9:711', 14, nid).rstrip('\n'))
        L.append(bind(f'9:900-{cp}-9:716', 18, nid).rstrip('\n'))
        L.append(f'            <Rectangle originX="0" originY="0" width="{CARD_W + 2 * CURSOR_OUT - 1}" height="{CARD_H + 2 * CURSOR_OUT - 1}" name="Path" id="{nid()}">')
        L.append('    ' + bind(f'9:900-{cp}-9:712', 20, nid).rstrip('\n'))
        L.append('    ' + bind(f'9:900-{cp}-9:713', 21, nid).rstrip('\n'))
        L.append('            </Rectangle>')
        L.append(f'            <Stroke thickness="1" name="Stroke" id="{nid()}">')
        L.append(f'                <SolidColor colorValue="{MARKER_COLOURS[i]}" name="Colour" id="{nid()}"/>')
        L.append(f'                <DashPath offset="{2 * i}" name="Dashes" id="{nid()}">')
        L.append(f'                    <Dash length="{DASH}" name="On" id="{nid()}"/>')
        L.append(f'                    <Dash length="{DASH}" name="Off" id="{nid()}"/>')
        L.append('                </DashPath>')
        L.append('            </Stroke>')
        L.append('        </Shape>')
    for i, c in enumerate(CHARS):
        x = CARD_X[i]
        CARD_Y = CARD_Y_ROW[i]
        L.append(f'        <Node name="Card{c.capitalize()}" id="{nid()}">')
        L.append(f'            <Image assetId="{I(c + "_stand")}" x="{x + 22}" y="{CARD_Y + 20}" originX="0" originY="0" name="stand" id="{nid()}">')
        L.append('    ' + bind(f'9:900-{LOCK_PROPS[i]}', 18, nid, '11:700').rstrip('\n'))
        L.append('            </Image>')
        L.append(f'            <Image assetId="{I(c + "_jump")}" x="{x + 22}" y="{CARD_Y + 20}" originX="0" originY="0" opacity="0" name="jump" id="{nid()}">')
        L.append('    ' + bind(f'9:900-{LOCK_PROPS[i]}', 18, nid).rstrip('\n'))
        L.append('            </Image>')
        L.append('    ' + text(x + 30, CARD_Y + 56, c.upper(), 'FFFFFFFF', 'Name', nid).replace('\n', '\n    '))
        L.append('    ' + text(x + 30, CARD_Y + 70, '', 'FFA0A0A0', 'Mode', nid).replace('\n', '\n    ').replace(
            'text="" name="Run" id="', 'text="" name="Run" id="').replace('/>\n            </Text>'.replace('\n', '\n    ') if False else '/>\n        </Text>'.replace('\n', '\n    '),
            '>\n                        <DataBindContext sourcePathIds="9:900-' + MODE_PROPS[i] + '" propertyKey="268" id="' + nid() + '"/>\n                    </TextValueRun>\n            </Text>'))
        L.append(f'            <Shape x="{x + 0.5}" y="{CARD_Y + 0.5}" name="Frame" id="{nid()}">')
        L.append(f'                <Rectangle originX="0" originY="0" width="{CARD_W - 1}" height="{CARD_H - 1}" name="Path" id="{nid()}"/>')
        L.append(f'                <Stroke thickness="1" name="Stroke" id="{nid()}"><SolidColor colorValue="{ORANGE}" name="Orange" id="{nid()}"/></Stroke>')
        L.append('            </Shape>')
        L.append('        </Node>')
    L.append(text(128, 4, 'MARIO BATTLE', 'FFFFFFFF', 'TitleText', nid))
    L.append(text(128, START_Y + 4, 'START', 'FFFFFFFF', 'StartText', nid))
    L.append(empty_machine('11', nid))
    L.append('    </Artboard>')
    L.append('    <ComponentAsset artboardId="11:100" name="Menu" id="11:102"/>')
    L.append(one_minus('One minus', '11:700'))
    L.append('</Rive>')
    return '\n'.join(L) + '\n'

for name, fn in [('hud_slot', hud_slot), ('overlay', overlay), ('menu', menu)]:
    path = os.path.join(root, 'scene/components', name + '.rml')
    open(path, 'w').write(fn())
    print('wrote', path)
