#!/usr/bin/env python3
"""writes scene/components/{spiny,fighter_fly,sidestepper}.rml. each enemy is a skin solo (normal, blue, and
for the crab angry, angry blue) of frame solos (walkA, walkB, flipped, dying). the script sets Enemy.pose
per frame like the rom's animation counter; Enemy.last and Enemy.angry pick the skin.
ids: spiny 2:xxx, fly 3:xxx, crab 4:xxx. run: python3 tools/gen_enemy_rml.py"""
import json, os
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ids = json.load(open(os.path.join(root, 'tools/asset_ids.json')))
def I(n): return f'8:{ids["image/" + n]}'

POSES = [("walkA", "walk_1", "9:121"), ("walkB", "walk_2", "9:124"), ("flipped", "flipped", "9:122"), ("dying", "flipped", "9:123")]

def enum_cond(prop_id, value_id):
    return f'''                        <TransitionViewModelCondition opValue="equal">
                            <TransitionPropertyViewModelComparator>
                                <BindablePropertyEnum>
                                    <DataBindContext sourcePathIds="9:400-{prop_id}" propertyKey="637"/>
                                </BindablePropertyEnum>
                            </TransitionPropertyViewModelComparator>
                            <TransitionValueEnumComparator value="{value_id}"/>
                        </TransitionViewModelCondition>'''

def bool_cond(prop_id, value):
    return f'''                        <TransitionViewModelCondition opValue="equal">
                            <TransitionPropertyViewModelComparator>
                                <BindablePropertyBoolean>
                                    <DataBindContext sourcePathIds="9:400-{prop_id}" propertyKey="634"/>
                                </BindablePropertyBoolean>
                            </TransitionPropertyViewModelComparator>
                            <TransitionValueBooleanComparator value="{value}"/>
                        </TransitionViewModelCondition>'''

def gen(client, name, title, prefix, skins, stage_x):
    """skins: list of (skinName, framePrefix, angry, last)"""
    c = client
    skin_solos = []
    for si, (skin, fp, _, _) in enumerate(skins):
        frames = "\n".join(
            f'                <Image assetId="{I(fp + "_" + frame)}" originX="0" originY="0" name="{pose}" id="{c}:{200 + si * 10 + pi}"/>'
            for pi, (pose, frame, _) in enumerate(POSES))
        skin_solos.append(f'''            <Solo activeComponentId="{c}:{200 + si * 10}" name="{skin}" id="{c}:{110 + si}">
{frames}
            </Solo>''')
    pose_anims = []
    for pi, (pose, _, _) in enumerate(POSES):
        keyed = "\n".join(
            f'            <KeyedObject objectId="{c}:{110 + si}"><KeyedProperty propertyKey="296"><KeyFrameId value="{c}:{200 + si * 10 + pi}" frame="0"/></KeyedProperty></KeyedObject>'
            for si in range(len(skins)))
        pose_anims.append(f'''        <LinearAnimation loopValue="loop" duration="1" name="{pose}" id="{c}:{400 + pi}">
{keyed}
        </LinearAnimation>''')
    skin_anims = []
    for si, (skin, _, _, _) in enumerate(skins):
        skin_anims.append(f'''        <LinearAnimation loopValue="loop" duration="1" name="skin {skin}" id="{c}:{420 + si}">
            <KeyedObject objectId="{c}:105"><KeyedProperty propertyKey="296"><KeyFrameId value="{c}:{110 + si}" frame="0"/></KeyedProperty></KeyedObject>
        </LinearAnimation>''')
    pose_states = []
    for pi, (pose, _, vid) in enumerate(POSES):
        trans = []
        for pj, (other, _, ovid) in enumerate(POSES):
            if pj == pi:
                continue
            trans.append(f'''                    <StateTransition stateToId="{c}:{520 + pj}" duration="0">
{enum_cond("9:410", ovid)}
                    </StateTransition>''')
        pose_states.append(f'''                <AnimationState animationId="{c}:{400 + pi}" x="{160 + pi * 140}" y="0" id="{c}:{520 + pi}">
{chr(10).join(trans)}
                </AnimationState>''')
    skin_states = []
    for si, (skin, _, angry, last) in enumerate(skins):
        trans = []
        for sj, (other, _, oangry, olast) in enumerate(skins):
            if sj == si:
                continue
            conds = [bool_cond("9:412", "true" if olast else "false")]
            if len(skins) == 4:
                conds.append(bool_cond("9:411", "true" if oangry else "false"))
            trans.append(f'''                    <StateTransition stateToId="{c}:{540 + sj}" duration="0">
{chr(10).join(conds)}
                    </StateTransition>''')
        skin_states.append(f'''                <AnimationState animationId="{c}:{420 + si}" x="{160 + si * 140}" y="0" id="{c}:{540 + si}">
{chr(10).join(trans)}
                </AnimationState>''')
    xml = f'''<Rive version="1" kind="fragment">
    <!-- generated by tools/gen_enemy_rml.py, do not edit by hand.
         {title}: 16x16. skins (normal, blue{", angry, angry blue" if len(skins) == 4 else ""}) of frame solos. the script sets
         Enemy.pose each frame the way the rom's animation counter picks a sprite; Enemy.last{" and Enemy.angry" if len(skins) == 4 else ""} pick the skin. -->
    <Artboard isComponent="true" defaultStateMachineId="{c}:500" viewModelId="9:400" viewModelInstanceId="9:401" width="16" height="16" styleId="{c}:101" x="{stage_x}" y="-120" name="{title}" id="{c}:100">
        <LayoutComponentStyle name="{title} Style" id="{c}:101"/>
        <Solo activeComponentId="{c}:110" name="Skin" id="{c}:105">
{chr(10).join(skin_solos)}
        </Solo>

{chr(10).join(pose_anims)}
{chr(10).join(skin_anims)}

        <StateMachine name="{title}" id="{c}:500">
            <StateMachineLayer name="Pose" id="{c}:501">
                <AnyState x="60" y="-100" id="{c}:502"/>
                <ExitState x="760" y="-100" id="{c}:503"/>
                <EntryState x="0" y="0" id="{c}:504">
                    <StateTransition stateToId="{c}:520" id="{c}:505"/>
                </EntryState>
{chr(10).join(pose_states)}
            </StateMachineLayer>
            <StateMachineLayer name="Skin" id="{c}:510">
                <AnyState x="60" y="-100" id="{c}:511"/>
                <ExitState x="760" y="-100" id="{c}:512"/>
                <EntryState x="0" y="0" id="{c}:513">
                    <StateTransition stateToId="{c}:540" id="{c}:514"/>
                </EntryState>
{chr(10).join(skin_states)}
            </StateMachineLayer>
        </StateMachine>
    </Artboard>
    <ComponentAsset artboardId="{c}:100" name="{title}" id="{c}:102"/>
</Rive>
'''
    open(os.path.join(root, f'scene/components/{name}.rml'), 'w').write(xml)
    print('wrote', name, len(xml.splitlines()), 'lines')

gen(2, 'spiny', 'Spiny', 'spiny', [("normal", "spiny", False, False), ("blue", "spiny_blue", False, True)], 40)
gen(3, 'fighter_fly', 'FighterFly', 'fly', [("normal", "fly", False, False), ("blue", "fly_blue", False, True)], 80)
gen(4, 'sidestepper', 'Sidestepper', 'crab', [("calm", "crab", False, False), ("calm blue", "crab_blue", False, True),
                                               ("angry", "crab_angry", True, False), ("angry blue", "crab_blue_angry", True, True)], 120)
